name: pgan-env
channels:
  - defaults
  - simpleitk
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python>=3.7
  - pip
  - wheel
  - tensorflow
  - tensorboard
  - torchvision>=0.5
  - cudatoolkit=10.1
  - pytorch
  - mlflow
  - dash
  - dask-core=2.12.0
  - decorator
  - defusedxml
  - entrypoints
  - graphite2>=1.3
  - grpcio=1.16.1
  - h5py
  - hdf5
  - imageio>=2.6.1
  - importlib_metadata>=1.5.0
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - nbconvert
  - kiwisolver
  - markdown
  - markupsafe
  - matplotlib>=3.1.3
  - memory_profiler
  - numpy>=1.18.1
  - mistune>=0.8.4
  - nbformat>=5.0
  - networkx>=2.4
  - ninja
  - notebook>=6.0
  - olefile>=0.46
  - opencv>=3.4
  - opt_einsum=3.1.0
  - pandas>=1.0
  - pandoc>=2.2
  - pandocfilters
  - parso=0.6.1
  - pexpect>=4.8
  - pickleshare=0.7
  - pillow>=7.0
  - pixman
  - plotly>=4.5
  - prometheus_client
  - protobuf
  - py-opencv
  - pydicom
  - pygments
  - pyparsing
  - pyrsistent
  - python-dateutil
  - pytz>=2019.3
  - pywavelets>=1.1.1
  - pyzmq>=18.1.1
  - retrying>=1.3.3
  - scikit-image>=0.16
  - scikit-learn>=0.22
  - scikit-plot>=0.3
  - scipy>=1.4
  - seaborn>=0.10.0
  - setuptools
  - simpleitk>=1.2.4
  - six
  - sqlite
  - testpath>=0.4
  - toolz>=0.10
  - tqdm
  - traitlets
  - wcwidth
  - webencodings
  - werkzeug
  - widgetsnbextension
  - wrapt
  - zeromq
  - zipp
  - zstd
  - pycodestyle=2.5.0
  - pylint=2.4.4
  - pytest
  - pytest-cov
